### PR TITLE
use ubuntu 21.04

### PR DESCRIPTION
**Pull request by individual-it**
we struggle to get the UI tests working with Ubuntu 21.10, but they work fine with 20.04

### CODE REVIEW

**Comment by TheOneRing** [comment]
If that works  we should probably partly revert https://github.com/owncloud-ci/client/commit/4fc6c570cbfb534def1e59887d2535dcbcca5430 and go back to a docker maintained by our admins.

But if I remember it correct there was a motivation for 21.10 https://github.com/owncloud-ci/client/pull/13 .
So 21.04 already provided Qt 5.15?

**Comment by individual-it** [comment]
@TheOneRing the tests run when compiling the master branch with 21.04 and run the tests with the same version see https://github.com/owncloud/client/pull/9244

**Comment by individual-it** [comment]
@TheOneRing yes 20.04 has QT 5.15 see https://packages.ubuntu.com/search?keywords=qt

**Comment by TheOneRing** [comment]
@fmoc ^

**Comment by fmoc** [comment]
> @TheOneRing yes 20.04 has QT 5.15 see https://packages.ubuntu.com/search?keywords=qt

Ubuntu focal/20.04 ships Qt 5.12.8. Starting with Ubuntu 21.04, Qt 5.15 is shipped.

We could base the Docker image on Ubuntu 21.04 for now, but we need to upgrade in March anyway because releases are EOL after nine months.

Alternatively, we could use third-party packages of Qt for building and testing, e.g., https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.2-focal. I'm not entirely sure how much work it will be to integrate third-party Qt packages, though. It might be easier to backport Qt 5.15 from a newer release by hand on OBS.

**Review by fmoc — APPROVED** [review]
Let's merge this for now and try to fix the issue with 21.10 afterwards.

**Pull request merged**
