### PR TITLE
Update kdsingleapplication

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by TheOneRing** [comment]
What is latest used for atm?
Can/should we drop it it appears to still be qt5.

**Review by fmoc — CHANGES_REQUESTED** [review]
Looks good code wise, but CI says no, please have a look.

**Comment by fmoc** [comment]
I see, it's "latest" which is failing. @saw-jan is that variant still in use for anything?

**Comment by saw-jan** [comment]
Latest is ubuntu-22.04 lts. The aim was to use linux distro that has long term support. But due to some problem related to showing gui with latest (ubuntu-22.04) image, we are using fedora image. `owncloud-ci/squish` depends on it so we had these multiple images.

**Comment by saw-jan** [comment]
> I see, it's "latest" which is failing. @saw-jan is that variant still in use for anything?

I looked at the drone config. I don't see we are actually using the ubuntu version of this image.

**Comment by TheOneRing** [comment]
So lets drop it?

**Comment by saw-jan** [comment]
I can't really say :thinking: . or just don't have to update latest fro now?
CC @fmoc

**Comment by fmoc** [comment]
Let's drop it. If need be, we'll just restore it from the Git history. Could you send a separate PR which we'll review separately and merge before this one?

**Pull request merged**
